language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: DOCTRINE_VERSION="2.2.*"
    - php: 7.2
      env: DOCTRINE_VERSION="2.3.*"
    - php: 7.2
      env: DOCTRINE_VERSION="2.4.*"
    - php: 7.2
      env: DOCTRINE_VERSION="2.5.*"
    - php: 7.2
      env: DOCTRINE_VERSION="2.6.*"

env:
  global:
    - DOCTRINE_VERSION=""
    - COMPOSER_FLAGS="--prefer-dist"

before_script:
  - composer self-update
  - if [ "$DOCTRINE_VERSION" != "" ]; then composer require --no-update doctrine/dbal:$DOCTRINE_VERSION doctrine/orm:$DOCTRINE_VERSION ; fi

install:
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

